# Generated by Django 4.0.5 on 2022-07-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serveraddress_ip_alter_serveraddress_port_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serveraddress',
            unique_together={('ip', 'port', 'port_iperf')},
        ),
    ]
