# Generated by Django 4.0.5 on 2022-08-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serveraddress_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveGstToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('acquired_service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_by', to='services.serveraddress')),
            ],
        ),
        migrations.AddIndex(
            model_name='fivegsttoken',
            index=models.Index(fields=['expires_at'], name='services_fi_expires_0fca10_idx'),
        ),
    ]
