# coding: utf-8

# flake8: noqa

"""
    Balancer

    Simple iperf load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: vinogradov.alek@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.client_api import ClientApi
from swagger_client.api.server_api import ServerApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.server_addr import ServerAddr
