# coding: utf-8

"""
    Balancer API

    Speedtest load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@5gst.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_acquire_create(self):
        """Test case for service_acquire_create

        """
        pass

    def test_service_create(self):
        """Test case for service_create

        """
        pass

    def test_service_delete(self):
        """Test case for service_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
