/*
 * Service API
 * Speedtest iperf service
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@5gst.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.scoltech.openran.speedtest.client.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IperfArgs
 */

public class IperfArgs {
  @SerializedName("iperf_args")
  private String iperfArgs = null;

  public IperfArgs iperfArgs(String iperfArgs) {
    this.iperfArgs = iperfArgs;
    return this;
  }

   /**
   * Get iperfArgs
   * @return iperfArgs
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIperfArgs() {
    return iperfArgs;
  }

  public void setIperfArgs(String iperfArgs) {
    this.iperfArgs = iperfArgs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IperfArgs iperfArgs = (IperfArgs) o;
    return Objects.equals(this.iperfArgs, iperfArgs.iperfArgs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iperfArgs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IperfArgs {\n");
    
    sb.append("    iperfArgs: ").append(toIndentedString(iperfArgs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

