services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "skoltech_db_name"
      POSTGRES_USER: "skoltech_db_user"
      POSTGRES_PASSWORD: "skoltech_db_pass"
    ports:
      - "5432:5432"
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "skoltech_db_name", "-U", "skoltech_db_user" ]
        interval: 5s
        timeout: 5s
        retries: 24

  balancer:
    image: skoltech/speedtest-balancer:0.3.0.30
    container_name: balancer
    depends_on:
        postgres:
            condition: service_healthy
            
    healthcheck:
        test: [ "CMD",  "curl", "-f", "curl http://10.16.160.104:8080/Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0/ping/"]
        interval: 5s
        timeout: 5s
        retries: 24
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG= ${DEBUG}
      - ALLOWED_HOSTS=127.0.0.1,${YOURE_IP}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - DB_NAME=skoltech_db_name
      - DB_USER=skoltech_db_user
      - DB_PASSWORD=skoltech_db_pass
      - DB_HOST=${YOURE_IP}
      - DB_PORT=5432
    ports:
      - "5555:8080"


  service_1: 
    image: skoltech/speedtest-service:0.3.0.30
    container_name: serv1 
    depends_on:
        balancer:
            condition: service_healthy
    environment:
      -  ALLOWED_HOSTS=127.0.0.1,${YOURE_IP}
      -  BALANCER_ADDRESS=${YOURE_IP}:5555
      -  BALANCER_BASE_URL=/Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0
      -  CONNECTING_TIMEOUT=30
      -  DEBUG=${DEBUG}
      -  IPERF_PORT=5005
      -  SECRET_KEY=${SECRET_KEY}
      -  SERVICE_IP_ADDRESS=${YOURE_IP}
      -  SERVICE_PORT=5004
    ports:
      -  "5004:5000"
      -  "5005:5005"
      -  "5005:5005/udp"
