/*
 * Balancer
 * Simple iperf load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: vinogradov.alek@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.ServerAddr;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerApi
 */
@Ignore
public class ServerApiTest {

    private final ServerApi api = new ServerApi();

    /**
     * delete server IP
     *
     * Send by server during shutdown.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverDeleteIpTest() throws ApiException {
        ServerAddr body = null;
        List<InlineResponse200> response = api.serverDeleteIp(body);

        // TODO: test validations
    }
    /**
     * post self ip to balancer
     *
     * When server makes free, post ip to balancer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serverPostIpTest() throws ApiException {
        ServerAddr body = null;
        api.serverPostIp(body);

        // TODO: test validations
    }
}
