/*
 * Balancer API
 * Speedtest load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@5gst.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ServerAddressRequest;
import io.swagger.client.model.ServerAddressResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalancerApi
 */
@Ignore
public class BalancerApiTest {

    private final BalancerApi api = new BalancerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skoltechOpenRAN5GIperfLoadBalancer010PingListTest() throws Exception {
        api.skoltechOpenRAN5GIperfLoadBalancer010PingList();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Acquires service for further iperf tests
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skoltechOpenRAN5GIperfLoadBalancer010ServiceAcquireCreateTest() throws Exception {
        ServerAddressResponse response = api.skoltechOpenRAN5GIperfLoadBalancer010ServiceAcquireCreate();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Register caller as service
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skoltechOpenRAN5GIperfLoadBalancer010ServiceCreateTest() throws Exception {
        ServerAddressRequest data = null;
        ServerAddressRequest response = api.skoltechOpenRAN5GIperfLoadBalancer010ServiceCreate(data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Unregister caller as service
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skoltechOpenRAN5GIperfLoadBalancer010ServiceDeleteTest() throws Exception {
        ServerAddressRequest data = null;
        ServerAddressRequest response = api.skoltechOpenRAN5GIperfLoadBalancer010ServiceDelete(data);

        // TODO: test validations
    }
    
}
