/*
 * Balancer API
 * Speedtest load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@5gst.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ServerAddressRequest;
import io.swagger.client.model.ServerAddressResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceApi
 */
@Ignore
public class ServiceApiTest {

    private final ServiceApi api = new ServiceApi();

    
    /**
     * 
     *
     * Acquires service for further iperf tests
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceAcquireCreateTest() throws Exception {
        ServerAddressResponse response = api.serviceAcquireCreate();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Register caller as service
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceCreateTest() throws Exception {
        ServerAddressRequest data = null;
        ServerAddressRequest response = api.serviceCreate(data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Unregister caller as service
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void serviceDeleteTest() throws Exception {
        ServerAddressRequest data = null;
        ServerAddressRequest response = api.serviceDelete(data);

        // TODO: test validations
    }
    
}
