# coding: utf-8

"""
    Balancer

    Simple iperf load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: vinogradov.alek@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.server_addr import ServerAddr  # noqa: E501
from swagger_client.rest import ApiException


class TestServerAddr(unittest.TestCase):
    """ServerAddr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerAddr(self):
        """Test ServerAddr"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_addr.ServerAddr()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
