# coding: utf-8

"""
    Balancer API

    Speedtest load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ServerAddressResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'str',
        'port': 'int',
        'port_iperf': 'int',
        'time': 'datetime'
    }

    attribute_map = {
        'ip': 'ip',
        'port': 'port',
        'port_iperf': 'port_iperf',
        'time': 'time'
    }

    def __init__(self, ip=None, port=None, port_iperf=None, time=None, _configuration=None):  # noqa: E501
        """ServerAddressResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ip = None
        self._port = None
        self._port_iperf = None
        self._time = None
        self.discriminator = None

        self.ip = ip
        self.port = port
        self.port_iperf = port_iperf
        self.time = time

    @property
    def ip(self):
        """Gets the ip of this ServerAddressResponse.  # noqa: E501


        :return: The ip of this ServerAddressResponse.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this ServerAddressResponse.


        :param ip: The ip of this ServerAddressResponse.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ip is None:
            raise ValueError("Invalid value for `ip`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ip is not None and len(ip) < 1):
            raise ValueError("Invalid value for `ip`, length must be greater than or equal to `1`")  # noqa: E501

        self._ip = ip

    @property
    def port(self):
        """Gets the port of this ServerAddressResponse.  # noqa: E501


        :return: The port of this ServerAddressResponse.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ServerAddressResponse.


        :param port: The port of this ServerAddressResponse.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                port is not None and port > 65535):  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value less than or equal to `65535`")  # noqa: E501
        if (self._configuration.client_side_validation and
                port is not None and port < 0):  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value greater than or equal to `0`")  # noqa: E501

        self._port = port

    @property
    def port_iperf(self):
        """Gets the port_iperf of this ServerAddressResponse.  # noqa: E501


        :return: The port_iperf of this ServerAddressResponse.  # noqa: E501
        :rtype: int
        """
        return self._port_iperf

    @port_iperf.setter
    def port_iperf(self, port_iperf):
        """Sets the port_iperf of this ServerAddressResponse.


        :param port_iperf: The port_iperf of this ServerAddressResponse.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and port_iperf is None:
            raise ValueError("Invalid value for `port_iperf`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                port_iperf is not None and port_iperf > 65535):  # noqa: E501
            raise ValueError("Invalid value for `port_iperf`, must be a value less than or equal to `65535`")  # noqa: E501
        if (self._configuration.client_side_validation and
                port_iperf is not None and port_iperf < 0):  # noqa: E501
            raise ValueError("Invalid value for `port_iperf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._port_iperf = port_iperf

    @property
    def time(self):
        """Gets the time of this ServerAddressResponse.  # noqa: E501


        :return: The time of this ServerAddressResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this ServerAddressResponse.


        :param time: The time of this ServerAddressResponse.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServerAddressResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerAddressResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServerAddressResponse):
            return True

        return self.to_dict() != other.to_dict()
