# coding: utf-8

# flake8: noqa
"""
    Service API

    Speedtest iperf service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: dev@5gst.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from service_api.models.iperf_args import IperfArgs
