# coding: utf-8

# flake8: noqa
"""
    Balancer API

    Speedtest load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: dev@5gst.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from balancer_api.models.five_gst_token import FiveGstToken
from balancer_api.models.server_address_request import ServerAddressRequest
from balancer_api.models.server_address_response import ServerAddressResponse
