# coding: utf-8

"""
    Balancer API

    Speedtest load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@5gst.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.server_address_request import ServerAddressRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestServerAddressRequest(unittest.TestCase):
    """ServerAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerAddressRequest(self):
        """Test ServerAddressRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_address_request.ServerAddressRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
