/*
 * Balancer
 * Simple iperf load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: vinogradov.alek@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * ServerAddr
 */

public class ServerAddr {
  @SerializedName("ip")
  private String ip = null;

  @SerializedName("port")
  private Integer port = null;

  @SerializedName("port_iperf")
  private Integer portIperf = null;

  @SerializedName("time")
  private OffsetDateTime time = null;

  public ServerAddr ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @Schema(example = "192.168.0.1", description = "")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public ServerAddr port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * port of Service server
   * minimum: 0
   * maximum: 65535
   * @return port
  **/
  @Schema(example = "5001", required = true, description = "port of Service server")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public ServerAddr portIperf(Integer portIperf) {
    this.portIperf = portIperf;
    return this;
  }

   /**
   * port of iperf server
   * minimum: 0
   * maximum: 65535
   * @return portIperf
  **/
  @Schema(example = "5000", required = true, description = "port of iperf server")
  public Integer getPortIperf() {
    return portIperf;
  }

  public void setPortIperf(Integer portIperf) {
    this.portIperf = portIperf;
  }

  public ServerAddr time(OffsetDateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(example = "2016-08-29T09:12:33.001Z", description = "")
  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(OffsetDateTime time) {
    this.time = time;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerAddr serverAddr = (ServerAddr) o;
    return Objects.equals(this.ip, serverAddr.ip) &&
        Objects.equals(this.port, serverAddr.port) &&
        Objects.equals(this.portIperf, serverAddr.portIperf) &&
        Objects.equals(this.time, serverAddr.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ip, port, portIperf, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerAddr {\n");
    
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    portIperf: ").append(toIndentedString(portIperf)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
