# coding: utf-8

# flake8: noqa
"""
    Balancer

    Simple iperf load balancer  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: vinogradov.alek@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.server_addr import ServerAddr
