name: "[Balancer] build docker image"

on: 
  pull_request:
    branches: [main, develop]

jobs:
  build-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./balancer
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build . --tag new_balancer_image
      
