name: "[Service] Build service image"

on: 
  pull_request:
    branches: [main, develop]



jobs:
  build-iperf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compilation
        run: ./scripts/build-iperf.sh

      - name: Setup artifact content
        run: |
          mkdir gh-artifacts
          mv iperf.elf gh-artifacts/
          
          IPERF_VERSION=$(cat ../iPerf/VERSION)
          echo "artifactName=iperf-$IPERF_VERSION.$GITHUB_RUN_NUMBER" > $GITHUB_ENV
      
      - name: Upload iperf binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: service/gh-artifacts/*

  speedtest-service:
    runs-on: ubuntu-latest
    needs: build-iperf
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup artifact name in env
        run: |
          IPERF_VERSION=$(cat ../iPerf/VERSION)
          echo "iPerfArtifactName=iperf-$IPERF_VERSION.$GITHUB_RUN_NUMBER" > $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.iPerfArtifactName }}
          path: service
      
      - name: Setup artifact content
        run: |
          cd ..
          mkdir gh-artifacts/
          cp -r service/* gh-artifacts/
          
          echo "artifactName=speedtest-service-$(cat service/VERSION).$GITHUB_RUN_NUMBER" > $GITHUB_ENV
      
      - name: Upload all server files to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: gh-artifacts/*
          
          
  build_image:
    runs-on: ubuntu-latest
    needs: speedtest-service
    defaults:
      run:
        working-directory: ./service
    steps:
      - uses: actions/checkout@v2
      - name: Setup version variable      
        run: echo "version=$(cat VERSION)" > $GITHUB_ENV
    
      - uses: actions/download-artifact@v2
        with:
          name: speedtest-service-${{ env.version }}.${{ github.run_number }}
          path: service/gh-artifacts
      - name: build image
        run: |
          git submodule init
          git submodule update
          docker build . --tag new_service_image
