name: "[Service] API client generation using swagger"

on: [push, pull_request]

jobs:
  generate-swagger:
    runs-on: ubuntu-latest
    env:
      SERVICE_IP_ADDRESS: localhost
      BALANCER_ADDRESS: localhost:5555
      IPERF_PORT: 5001
      SERVICE_PORT: 5000
      SECRET_KEY: test
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v3

      - name: Install pip, pipenv and packages from Pipfile
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Generate swagger schema
        run: |
          pipenv run python manage.py generate_swagger swagger.yaml

      - name: Upload swagger schema to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swagger-schema
          path: service/swagger.yaml

  generate-code:
    runs-on: ubuntu-latest
    needs: generate-swagger
    container: swaggerapi/swagger-codegen-cli:2.4.27
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v3

      - name: Download swagger schema
        uses: actions/download-artifact@v2
        with:
          name: swagger-schema
          path: service

      - name: Clear AUTOBUILD directory
        run: rm -rf ../AUTOBUILD

      - name: Generate client for service
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i swagger.yaml
          -l python
          -o ../AUTOBUILD/balancer2ServiceClient/
          -c ../balancer/.swagger-codegen-config/serviceApi.json

      - name: Generate client for application
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i swagger.yaml
          -l java
          -o ../AUTOBUILD/application2ServiceClient/
          -c ../application/.swagger-codegen-config/serviceApi.json

      # Swagger codegen container has invalid git installed,
      # so we need another container to push changes
      - name: Upload generated code to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AUTOBUILD
          path: AUTOBUILD

  push:
    runs-on: ubuntu-latest
    needs: generate-code
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

      - name: Clear previously generated code
        run: |
          rm -rf ../AUTOBUILD
          rm -rf ../application/serviceApi
          rm -rf ../balancer/service_api

      - name: Download generated code
        uses: actions/download-artifact@v2
        with:
          name: AUTOBUILD
          path: AUTOBUILD

      - name: Move generated code to projects
        run: |
          cp -r ../AUTOBUILD/application2ServiceClient/ ../application/serviceApi
          cp -r ../AUTOBUILD/balancer2ServiceClient/service_api/ ../balancer/service_api
#          TODO
#          cd ../application
#          git apply ./.swagger-codegen-config/serviceApi.patch

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: 'Generate service client using swagger-codegen'
            file_pattern: application/serviceApi balancer/service_api
