/*
 * Balancer
 * Simple iperf load balancer
 *
 * OpenAPI spec version: 0.1.0
 * Contact: vinogradov.alek@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ServerAddr;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientApi
 */
@Ignore
public class ClientApiTest {

    private final ClientApi api = new ClientApi();

    /**
     * obtain iperf server ip list to connect to
     *
     * Return servers ip list
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clientObtainIpTest() throws ApiException {
        List<ServerAddr> response = api.clientObtainIp();

        // TODO: test validations
    }
}
